# your code should include everybody and the
# best way to do that is to avoid excluding
# anybody.

[contributors]
contributors = [
  "nadya"
]

[exclusives]
words = [
  "aunt",
  "boyfriend",
  "boys",
  "brother",
  "caveman",
  "chairman",
  "cousin",
  "crazy",
  "daughter",
  "dumb",
  "family",
  "father",
  "fathering",
  "fiance",
  "foreman",
  "friend(s)",
  "girlfriend",
  "girls",
  "grandfather",
  "grandfathered",
  "grandfathering",
  "grandmother",
  "guys",
  "hacker",
  "he",
  "her",
  "herself",
  "himself",
  "his",
  "human",
  "husband",
  "insane",
  "it's easy",
  "it's simple",
  "lame",
  "man hours",
  "man",
  "manpower",
  "mom test",
  "mother",
  "mothering",
  "ninja",
  "normal",
  "painful",
  "people",
  "person",
  "orphan",
  "rockstar",
  "she",
  "significant other",
  "sister",
  "so easy",
  "son",
  "spouse",
  "stupid",
  "suffer",
  "uncle",
  "wife",
  "woman"
]

# remember to use inclusive terminology
# put people first
# avoid idioms and acronyms
